# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='speaker',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='sponsor',
        ),
    ]
