# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_auto_20160608_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='conference',
            field=models.ManyToManyField(null=True, to='conference.Conference'),
        ),
    ]
