# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_auto_20160608_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='conference',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
