# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_auto_20160608_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
