# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_auto_20160608_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='conference',
            field=models.ManyToManyField(to='conference.Conference'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
