# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_auto_20160608_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('view_sponsors', 'Can view sponsors list'), ('add_representative', 'Can add representative'), ('set_speaker', 'Can set speaker'))},
        ),
    ]
